--function ProcessRequest(reqIndex, request)
--
--end
--
--function OnTick(event)
--    local tick = event.tick
--
--    local dispatcher_updates_per_tick = 1;
--
--    if global.tick_state == 1 then
--    else
--        for i = 1, dispatcher_updates_per_tick, 1 do
--
--        end
--    end
--end